<a href="https://colab.research.google.com/github/stacykeago/predictive-data-analytics/blob/main/PDA_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Define the question:

# Metric of success
The likelihood of a claim being rejected could be evaluated based on several key performance indicators (KPIs) commonly used in machine learning classification tasks.
1. Accuracy
2. Precision
3. Recall (Sensitivity)
4. F1 Score
5. Area Under the ROC Curve (AUC-ROC)
6. Confusion Matrix

Resources that support this analysis
1. [Business Insights & Recommendations](https://docs.google.com/document/d/1q9gwblcG5X_Cm1P03Y4Zzbr2ue-CVVN8ecXmyi_yRAM/edit?usp=sharing)
2.

# Data used:
1. [link to kaggle dataset ](https://www.kaggle.com/datasets/itszubi/ai-workforce-displacement-and-automation-trends/data)

# a. EXPLORATTORY DATA ANALYSIS (EDA)

## 1.0 Import the libraries to be used

In [48]:
import numpy as np # for linear algebra
import pandas as pd # for data processing
import matplotlib.pyplot as plt # for data visualization
import seaborn as sns # for statistical data visualization
from sklearn.preprocessing import LabelEncoder # the libraries for label encoding

## 2.0 Upload Dataset

In [52]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

# 1. Set the precise filename you provided
file_path = "ai_workforce_displacement_global_2020_2026.csv"

# 2. Load the dataset using kagglehub
work = kagglehub.dataset_load(
    KaggleDatasetAdapter.PANDAS,
    "itszubi/ai-workforce-displacement-and-automation-trends",
    file_path
)

# 3. View the first 5 records

work.head(10)

Using Colab cache for faster access to the 'ai-workforce-displacement-and-automation-trends' dataset.

,record_id,country,iso3_code,region,income_group,year,quarter,quarter_label,industry_sector,sector_automation_risk_score,gdp_per_capita_usd,ai_adoption_index,pct_sector_workforce_displaced,pct_sector_workforce_new_roles_created,net_workforce_change_pct,ai_cited_layoff_announcements,ai_skill_wage_premium_pct,pct_workforce_female,pct_displaced_roles_female,reskilling_programs_count,govt_ai_policy_score_1_to_10,ai_tool_adoption_pct,data_source_notes
0,1,United States,USA,North America,High Income,2020,1,2020-Q1,Technology & Software,0.382,63514,0.830,0.0406,0.0348,-0.0058,32,0.311,0.28,0.275,52,6.4,0.280,Research-calibrated synthetic data. Grounded i...
1,2,United States,USA,North America,High Income,2020,1,2020-Q1,Finance & Banking,0.608,63514,0.817,0.0517,0.0423,-0.0094,51,0.304,0.48,0.511,39,6.5,0.559,Research-calibrated synthetic data. Grounded i...
2,3,United States,USA,North America,High Income,2020,1,2020-Q1,Healthcare & Life Sciences,0.198,63514,0.816,0.0176,0.0168,-0.0008,4,0.278,0.72,0.707,37,6.8,0.202,Research-calibrated synthetic data. Grounded i...
3,4,United States,USA,North America,High Income,2020,1,2020-Q1,Manufacturing & Industry,0.720,63514,0.818,0.0924,0.0642,-0.0282,47,0.268,0.29,0.310,50,6.8,0.655,Research-calibrated synthetic data. Grounded i...
4,5,United States,USA,North America,High Income,2020,1,2020-Q1,Retail & E-Commerce,0.676,63514,0.828,0.0667,0.0374,-0.0293,31,0.313,0.54,0.547,37,6.2,0.542,Research-calibrated synthetic data. Grounded i...
5,6,United States,USA,North America,High Income,2020,1,2020-Q1,Education & Research,0.287,63514,0.822,0.0290,0.0237,-0.0053,6,0.328,0.58,0.631,39,6.7,0.265,Research-calibrated synthetic data. Grounded i...
6,7,United States,USA,North America,High Income,2020,1,2020-Q1,Transportation & Logistics,0.694,63514,0.810,0.0713,0.0645,-0.0068,43,0.273,0.22,0.214,40,6.4,0.487,Research-calibrated synthetic data. Grounded i...
7,8,United States,USA,North America,High Income,2020,1,2020-Q1,Media & Communications,0.565,63514,0.843,0.0507,0.0416,-0.0091,25,0.289,0.46,0.480,52,6.5,0.475,Research-calibrated synthetic data. Grounded i...
8,9,United States,USA,North America,High Income,2020,1,2020-Q1,Administrative & Clerical,0.793,63514,0.819,0.1044,0.0736,-0.0308,62,0.344,0.79,0.950,53,6.6,0.546,Research-calibrated synthetic data. Grounded i...
9,10,United States,USA,North America,High Income,2020,1,2020-Q1,Energy & Utilities,0.443,63514,0.805,0.0390,0.0216,-0.0174,13,0.263,0.26,0.274,53,7.3,0.291,Research-calibrated synthetic data. Grounded i...

### Column names

In [53]:
work.columns

Index(['record_id', 'country', 'iso3_code', 'region', 'income_group', 'year',
       'quarter', 'quarter_label', 'industry_sector',
       'sector_automation_risk_score', 'gdp_per_capita_usd',
       'ai_adoption_index', 'pct_sector_workforce_displaced',
       'pct_sector_workforce_new_roles_created', 'net_workforce_change_pct',
       'ai_cited_layoff_announcements', 'ai_skill_wage_premium_pct',
       'pct_workforce_female', 'pct_displaced_roles_female',
       'reskilling_programs_count', 'govt_ai_policy_score_1_to_10',
       'ai_tool_adoption_pct', 'data_source_notes'],
      dtype='object')

### 2.1 Number of rows and columns

In [54]:
# Print number of rows and columns
print(f"Rows: {work.shape[0]}, Columns: {work.shape[1]}")

Rows: 20800, Columns: 23

### 2.2 Data types in each column

In [55]:
work.dtypes

record_id                                   int64
country                                    object
iso3_code                                  object
region                                     object
income_group                               object
year                                        int64
quarter                                     int64
quarter_label                              object
industry_sector                            object
sector_automation_risk_score              float64
gdp_per_capita_usd                          int64
ai_adoption_index                         float64
pct_sector_workforce_displaced            float64
pct_sector_workforce_new_roles_created    float64
net_workforce_change_pct                  float64
ai_cited_layoff_announcements               int64
ai_skill_wage_premium_pct                 float64
pct_workforce_female                      float64
pct_displaced_roles_female                float64
reskilling_programs_count                   int64
govt_ai_policy_score_1_to_10              float64
ai_tool_adoption_pct                      float64
data_source_notes                          object
dtype: object

### 2.3 Basic info of the data

In [56]:
# Display basic information about the columns
print(work.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20800 entries, 0 to 20799
Data columns (total 23 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   record_id                               20800 non-null  int64
 1   country                                 20800 non-null  object
 2   iso3_code                               20800 non-null  object
 3   region                                  20800 non-null  object
 4   income_group                            20800 non-null  object
 5   year                                    20800 non-null  int64
 6   quarter                                 20800 non-null  int64
 7   quarter_label                           20800 non-null  object
 8   industry_sector                         20800 non-null  object
 9   sector_automation_risk_score            20800 non-null  float64
 10  gdp_per_capita_usd                      20800 non-null  int64
 11  ai_adoption_index                       20800 non-null  float64
 12  pct_sector_workforce_displaced          20800 non-null  float64
 13  pct_sector_workforce_new_roles_created  20800 non-null  float64
 14  net_workforce_change_pct                20800 non-null  float64
 15  ai_cited_layoff_announcements           20800 non-null  int64
 16  ai_skill_wage_premium_pct               20800 non-null  float64
 17  pct_workforce_female                    20800 non-null  float64
 18  pct_displaced_roles_female              20800 non-null  float64
 19  reskilling_programs_count               20800 non-null  int64
 20  govt_ai_policy_score_1_to_10            20800 non-null  float64
 21  ai_tool_adoption_pct                    20800 non-null  float64
 22  data_source_notes                       20800 non-null  object
dtypes: float64(10), int64(6), object(7)
memory usage: 3.7+ MB
None

### 2.4 Null values

In [57]:
# To check for Null values to ensures the integrity of your dataset.
work.isnull().sum()

record_id                                 0
country                                   0
iso3_code                                 0
region                                    0
income_group                              0
year                                      0
quarter                                   0
quarter_label                             0
industry_sector                           0
sector_automation_risk_score              0
gdp_per_capita_usd                        0
ai_adoption_index                         0
pct_sector_workforce_displaced            0
pct_sector_workforce_new_roles_created    0
net_workforce_change_pct                  0
ai_cited_layoff_announcements             0
ai_skill_wage_premium_pct                 0
pct_workforce_female                      0
pct_displaced_roles_female                0
reskilling_programs_count                 0
govt_ai_policy_score_1_to_10              0
ai_tool_adoption_pct                      0
data_source_notes                         0
dtype: int64

No null values in the auto dataset

### 2.5 Duplicates

In [58]:
#check for duplicates : Duplicates are noise to the data
np.sum(work.duplicated())

np.int64(0)

### 2.6 Unique features in the data

In [59]:
# count of unique values for each column in the DataFrame.
work.nunique()

record_id                                 20800
country                                      80
iso3_code                                    80
region                                       12
income_group                                  4
year                                          7
quarter                                       4
quarter_label                                26
industry_sector                              10
sector_automation_risk_score                679
gdp_per_capita_usd                         1981
ai_adoption_index                           775
pct_sector_workforce_displaced             2068
pct_sector_workforce_new_roles_created     1680
net_workforce_change_pct                    837
ai_cited_layoff_announcements               519
ai_skill_wage_premium_pct                   490
pct_workforce_female                         10
pct_displaced_roles_female                  453
reskilling_programs_count                    91
govt_ai_policy_score_1_to_10                 78
ai_tool_adoption_pct                        799
data_source_notes                             1
dtype: int64

### 2.7 Outliers

# b. Univariate Analysis

# c. Bivariate Analysis

# d. Multivariate Analysis

## Feature selection
• What features seem most related to price?

# HYPOTHESIS TESTING
1. Does higher horsepower always mean higher price?